import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="content">
          <Navbar />
          {children}
          <Footer/>
        </div>
        </body>
    </html>
  );
}
